database:
  host: ""
  port: 3306
  database: ""
  username: ""
  password: ""
  # Использовать SSL соединение?
  useSSL: false
  # Переподключаться к базе данных при потере соединения?
  autoReconnect: true

messages:
  # Сообщение игроку, пригласил ли его кто-то на сервер или нет, которое будет отправлено при первом заходе
  # Можно использовать цвета с форматированием "&"
  referral-question: "&aДобро пожаловать в клуб, новичок!\n&fПожалуйста, напиши никнейм игрока, который пригласил вас, или же просто оставьте знак тире, мы поймём, что вы нашли нас другим способом!"
  # Сообщение игроку, если он ответил на вопрос об приглашение на сервер существующим игроком
  referral-agree: "Игроку &a%s &fбыл отправлен бонус за приглашение!"
  # Сообщение игроку, если он решил не отвечать на вопрос об приглашение на сервер
  referral-disagree: "Очень жаль :(\nСпасибо за участие в опросе!"
  # Сообщение игроку, если он ответил на вопрос об приглашение на сервер несуществующим игроком
  referral-player-not-exists: "&4Данного игрока не существует, пожалуйста, введите другой никнейм, или откажитесь от вопроса, написав тире"

answers:
  negative:
    - "-"
    - "нет"
    - "не знаю"
    - "не помню"
    - "не приглашал"
    - "не приглашала"
    - "не приглашали"
    - "хуй знает"
    - "хуй пойми"
    - "я ебу"
    - "я хз"
    - "да хуй знает"
    - "да хуй пойми"
    - "да я ебу"
    - "да я не ебу"
    - "да я хз"
    - "иди нахуй"
    - "пошёл нахуй"
    - "я сам нашёл"
    - "я сама нашла"