database:
  host: ""
  port: 3306
  database: ""
  username: ""
  password: ""
  # Использовать SSL соединение?
  useSSL: false
  # Переподключаться к базе данных при потере соединения?
  autoReconnect: true

messages:
  # Сообщение игроку, пригласил ли его кто-то на сервер или нет, которое будет отправлено при первом заходе
  # Можно использовать цвета с форматированием "&"
  referral-question: "&aДобро пожаловать в клуб, новичок!\n&fПожалуйста, напиши никнейм игрока, который пригласил вас, или же просто оставьте знак тире, мы поймём, что вы нашли нас другим способом!"
  # Сообщение игроку, если он ответил на вопрос об приглашение на сервер существующим игроком
  referral-agree: "Игроку &a%s &fбыл отправлен бонус за приглашение!"
  # Сообщение игроку, если он решил не отвечать на вопрос об приглашение на сервер
  referral-disagree: "Очень жаль :(\nСпасибо за участие в опросе!"
  # Сообщение игроку, если он ответил на вопрос об приглашение на сервер несуществующим игроком
  referral-player-not-exists: "&4Данного игрока не существует, пожалуйста, введите другой никнейм, или откажитесь от вопроса, написав тире"
  # Сообщение игроку, которое будет отправлено при поиске игрока в реферальной системе
  find-player-message:
  - "&7Введите ник игрока, которого вы хотите найти:"
  - "&7Для отмены напишите негативный ответ"

descriptions:
  # Описание меню /invite
  invite-gui-explanation:
  - "&7Здесь вы можете увидеть список приглашённых вами игроков."
  - "&7Также можно увидеть информацию о них."
  - "&7Если вы никого не видите, то скорее приглашайте друзей на сервер и получайте бонусы!"
  # Описание меню /admininvite
  admin-invite-gui-explanation:
    - "&7Здесь вы можете увидеть список игроков, которые участвуют в реферальной системе."
    - "&7Наведя на игрока, вы увидите информацию о нём."
    - "&7Если игрок пригласил другого игрока, то нажмите &fЛКМ &7на него, чтобы увидеть список приглашённых."
    - "&7Если вы считаете, что информация об игроке неактуальна, нажмите &fПКМ&7, чтобы обновить её."
  # Описание предмета "Назад" в реферальной системе (информация об игроке -> реферальная система)
  back-item-description: "&7Нажмите, чтобы вернуться назад к &fреферальной системе"
  # Описание предмета "Найти игрока" в реферальной системе
  find-player-item-description:
  - "&7Нажмите, чтобы найти игрока"
  # Описание предмета поиска, если ничего не найдено
  no-player-found-item-description:
  - "&7По запросу &f%s &7ничего не найдено."
  - "&7Нажмите, чтобы вернуться назад к &fреферальной системе"
  # Описание предмета в /invite, если игрока никто не пригласил
  not-invited-item-description:
  - "&7Вы не были приглашены на сервер."
  - "&7Но если вас всё же кто-то пригласил, то нажмите &fсюда"

answers:
  negative:
    - "нет"
    - "не знаю"
    - "не помню"
    - "не приглашал"
    - "не приглашала"
    - "не приглашали"
    - "хуй знает"
    - "хуй пойми"
    - "я ебу"
    - "я хз"
    - "да хуй знает"
    - "да хуй пойми"
    - "да я ебу"
    - "да я не ебу"
    - "да я хз"
    - "иди нахуй"
    - "пошёл нахуй"
    - "я сам нашёл"
    - "я сама нашла"